travis:
  secure:
    BINSTAR_TOKEN: mZI0ZEjDjnQ96l9ZTm75bAXlkI4gx+o44Vaf5FO305B27j5O8VQYPNmdSLULjMX1bDwuzCnztWFn1v8yHdKN3qpE5DzC0krOcSVnxtVf2Us+H/saS0eknCsOVoL3ewuS0x5GFbd5iC6ImbqqniIrku6mBjNZZKBz8yGaqJsxf5aK5xDDfyeKnyzKge+C/RCSUMzbQB93NwbuARME5NHSzMPVXusoX/JK8+HKjDbGNVsHdj0vyGx/zMQkc6NObP9hidDNxywIAmctq4N68ieLxCTvl/OjcpNx/jXmj3CFUTKFbWTqDGbE7BY+ihj4BZEH2V993GKskyEuwbN2Fo/hmIuHiQuNvQQfRygWM1xaHCEYbYhdIM3R6Bmu5eQ87iE61HIveTLN1mYYNSJK1UDJ1pC58ObRiHm/vEyecuGAzw5iT+jgd5Z0ur5HITchrJHbsccpBdP8OntCeB2+8ZXs6+r7uLNnQOsxn7Mshdjp3FCJV3jtPPZRGKrbfh7j4USWaEZMnCE1uvgQYsngiDzzk9dhK3D0P9x9u393hWc0RFIDGRne5IW/xYzrMdDKVZTRFnC/QGGrbPmjKXn+1AunZMQzH07H5XpfJNfT33ugirDcrlwRX2b+7kwmrZVBSyoZPXWx4a2NGz2mx9ac221BMswlhaa/YW9r3ntCsu9Mn4M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
