travis:
  secure:
    BINSTAR_TOKEN: Iz2k1rmjO2uQ/o+8vaU6NB9sxMFPbmEc08ff1N2wzuKPDshlR0FbldR5NzH2exQpwVO/kHPq+ieWIU3VtBg+qkDfplNrikE08cRcrqsnbGkMql6NmyC5U1wzmWYgC/aQkH5RIYoYjCZQsu09iUFpiIL+9tfeQRPUkpVw9bDD2eSWhdJi3BWd402r73e6ZMvy1ZgO8HgTOFNjOmGcVthkX/ugMn+XBJo6cFUqZeR0Fwk7GE6WvGc1v22YsIMRaRGcvGLuhZ0EC+uIfUmLIYN+ucg7IeGIdCGVB9q9daN2JsaE111nOmF3QBqQmBC+EAsz+liu2rR3hQiKDnS1Bl/r3UiDX5ItBRErvItqBpksIaTqpmCYL9jdlbBVRvQq/S4Ol50kaZot0xU0vAEyhb8RXOmSezQ/OYGqaGFgf/EQAnVNmtroBECUs8S2KsNPDBfSJAodQop0dLSw642ZZVULaJ5zhP4VMHWF3MEuKRSkQva1Uce1WBQiyYo9Topb+3Itx0LIGHxtTy2juAwUr5qSuHnEX4hekn6ODZn1e0DlqGQCwfzIO9xyOtGCIn3cP8lT6tJ1lM6VtqPpNO57j6yeGYiMu+F/Hjj3yM5UwcXWeLdMb3wJ0TpGW6tMQvEv0+9tcLVAbMr3nWhh9ksvNmWbLDX94eXKswTYH00XdzR6krU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
